FROM debian:bullseye
WORKDIR /app

RUN apt-get update \
    && apt-get dist-upgrade -y

RUN apt install -y curl\
    procps\
    iproute2\
    systemctl\
    tor\
    privoxy\
    git\
    iptables\
    gnupg\
    sudo

# // Simulation stop service failure
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# my notes
# Build and push image
# docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/tn00869679/torcontroller/torcontroller-test-env:dev -f dockerfile.testenv --push .
